# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# parameters:
# - name: environment_name
#   type: string
# - name: environment_file
#   type: string

# steps:
#   - task: AzureCLI@2
#     displayName: Register Azure ML environment 
#     continueOnError: true
#     inputs: 
#       azureSubscription: $(ado_service_connection_rg) #needs to have access at the RG level 
#       scriptType: bash
#       workingDirectory: $(System.DefaultWorkingDirectory)
#       scriptLocation: inlineScript
#       inlineScript: |
#         az ml environment create --name ${{ parameters.environment_name }} --file ${{ parameters.environment_file }}

parameters:
  - name: environment_name
    type: string
  - name: environment_description
    type: string
    default: ""
  - name: environment_file
    type: string
  - name: build_type
    type: string

steps:

- task: AzureCLI@2
  displayName: Register training environment
  inputs:
    azureSubscription: $(ado_service_connection_aml_ws)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az ml environment create --name "${{parameters.environment_name}}" \
        --description "${{parameters.environment_description}}" \
        --file "${{parameters.environment_file}}" \
        --build "${{parameters.build_type}}"
